### ISSUE TITLE
silence run fails when api folder contains a file that does not describe an endpoint

### ISSUE THREAD

**Issue by druizcortes** [DEAL-US/Silence#2]
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\silence.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\silence\cli\manager.py", line 35, in run_from_command_line
    HANDLERS[args.command.lower()](args.options)
  File "c:\program files\python38\lib\site-packages\silence\cli\commands\run.py", line 10, in handle
    server_manager.setup()
  File "c:\program files\python38\lib\site-packages\silence\server\manager.py", line 76, in setup
    load_user_endpoints()
  File "c:\program files\python38\lib\site-packages\silence\server\endpoint_loader.py", line 26, in load_user_endpoints
    raise RuntimeError(f"Could not load the API file {module_name}")
RuntimeError: Could not load the API file api.slides

**Comment by agu-borrego** [comment]
Should be fixed in [1.0.7](https://github.com/IISSI-US/Silence/releases/tag/1.0.7)!
